"""Report generation endpoints for Imaging Intelligence Agent.

POST /reports/generate -- Generate a structured clinical report
from a RAG query, including evidence citations and optional PDF output.

Author: Adam Jones
Date: February 2026
"""

import time
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from loguru import logger
from pydantic import BaseModel, Field
from starlette.responses import Response

# =====================================================================
# Request / Response Models
# =====================================================================


class ReportRequest(BaseModel):
    """Report generation request."""
    question: str = Field(..., min_length=3, max_length=2000, description="Clinical question")
    modality: Optional[str] = Field(None, description="Imaging modality filter")
    body_region: Optional[str] = Field(None, description="Body region filter")
    top_k: int = Field(5, ge=1, le=30, description="Results per collection")
    format: str = Field("markdown", description="Output format: markdown, json, or pdf")
    include_evidence: bool = Field(True, description="Include evidence citations in report")
    report_title: str = Field("", description="Custom report title (optional)")


class EvidenceCitation(BaseModel):
    """A single evidence citation in the report."""
    collection: str
    id: str
    score: float
    text_snippet: str = ""
    label: str = ""


class ReportResponse(BaseModel):
    """Generated report response (for markdown and json formats)."""
    title: str
    generated_at: str
    question: str
    answer: str
    evidence: List[EvidenceCitation] = []
    evidence_count: int
    collections_searched: int
    search_time_ms: float
    generation_time_ms: float
    format: str
    content: str = Field("", description="Full rendered report content (markdown or json string)")


# =====================================================================
# Report Rendering
# =====================================================================


def _render_markdown_report(
    title: str,
    question: str,
    answer: str,
    evidence: List[EvidenceCitation],
    search_time_ms: float,
) -> str:
    """Render a Markdown-formatted clinical report."""
    lines = [
        f"# {title}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Search time:** {search_time_ms:.0f}ms",
        "",
        "---",
        "",
        "## Clinical Question",
        "",
        question,
        "",
        "## Analysis",
        "",
        answer,
        "",
    ]

    if evidence:
        lines.extend([
            "---",
            "",
            f"## Evidence ({len(evidence)} citations)",
            "",
        ])
        for i, cite in enumerate(evidence, 1):
            score_pct = cite.score * 100
            lines.append(
                f"{i}. **[{cite.label or cite.collection}]** "
                f"`{cite.id}` (relevance: {score_pct:.1f}%)"
            )
            if cite.text_snippet:
                lines.append(f"   > {cite.text_snippet[:300]}")
            lines.append("")

    lines.extend([
        "---",
        "",
        "*This report was generated by the HCLS AI Factory -- Imaging Intelligence Agent. "
        "All findings require verification by a qualified radiologist. "
        "For research purposes only.*",
    ])

    return "\n".join(lines)


def _render_pdf_report(
    title: str,
    question: str,
    answer: str,
    evidence: List[EvidenceCitation],
    search_time_ms: float,
) -> bytes:
    """Render a PDF-formatted clinical report using reportlab."""
    from io import BytesIO

    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    from reportlab.lib import colors

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=18, spaceAfter=12,
    )
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
        f"Search time: {search_time_ms:.0f}ms",
        styles["Normal"],
    ))
    story.append(Spacer(1, 18))

    # Clinical Question
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], fontSize=14, spaceBefore=12, spaceAfter=6,
    )
    story.append(Paragraph("Clinical Question", heading_style))
    story.append(Paragraph(question, styles["Normal"]))
    story.append(Spacer(1, 12))

    # Analysis
    story.append(Paragraph("Analysis", heading_style))
    # Split answer into paragraphs for better formatting
    for para in answer.split("\n\n"):
        cleaned = para.strip().replace("\n", "<br/>")
        if cleaned:
            story.append(Paragraph(cleaned, styles["Normal"]))
            story.append(Spacer(1, 6))
    story.append(Spacer(1, 12))

    # Evidence
    if evidence:
        story.append(Paragraph(f"Evidence ({len(evidence)} citations)", heading_style))

        for i, cite in enumerate(evidence[:15], 1):
            score_pct = cite.score * 100
            cite_text = (
                f"<b>{i}. [{cite.label or cite.collection}]</b> "
                f"<font size='8'>{cite.id}</font> "
                f"(relevance: {score_pct:.1f}%)"
            )
            story.append(Paragraph(cite_text, styles["Normal"]))
            if cite.text_snippet:
                snippet_style = ParagraphStyle(
                    "Snippet", parent=styles["Normal"],
                    fontSize=8, leftIndent=20, textColor=colors.gray,
                )
                story.append(Paragraph(cite.text_snippet[:250], snippet_style))
            story.append(Spacer(1, 4))

    # Disclaimer
    story.append(Spacer(1, 24))
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=colors.gray, alignment=1,
    )
    story.append(Paragraph(
        "This report was generated by the HCLS AI Factory -- Imaging Intelligence Agent. "
        "All findings require verification by a qualified radiologist. For research purposes only.",
        disclaimer_style,
    ))

    doc.build(story)
    return buffer.getvalue()


# =====================================================================
# Router
# =====================================================================

router = APIRouter()


def _get_state():
    """Import and access the shared application state from api.main."""
    from api.main import _state
    return _state


@router.post("/reports/generate")
async def generate_report(request: ReportRequest):
    """Generate a structured clinical report from a RAG query.

    Supports three output formats:
      - markdown: Returns ReportResponse with rendered Markdown in `content`
      - json: Returns ReportResponse with full structured data
      - pdf: Returns binary PDF file as download

    The report includes:
      - Clinical question
      - RAG-synthesized analysis
      - Evidence citations with relevance scores
      - Timestamp and metadata
    """
    start = time.time()
    state = _get_state()

    engine = state.get("engine")
    if engine is None:
        raise HTTPException(status_code=503, detail="Agent engine not initialized")

    # Build search kwargs
    kwargs = {"top_k_per_collection": request.top_k}
    if request.modality:
        kwargs["modality_filter"] = request.modality

    try:
        # Retrieve evidence
        evidence = engine.retrieve(request.question, **kwargs)

        # Synthesize answer
        answer = engine.query(request.question, **kwargs)
    except Exception as e:
        logger.error(f"Report generation failed during RAG: {e}")
        raise HTTPException(status_code=500, detail=f"RAG query failed: {e}")

    # Build evidence citations
    from src.rag_engine import COLLECTION_CONFIG

    citations = []
    if request.include_evidence:
        for hit in evidence.hits[:20]:
            config = COLLECTION_CONFIG.get(hit.collection, {})
            citations.append(EvidenceCitation(
                collection=hit.collection,
                id=hit.id,
                score=hit.score,
                text_snippet=hit.text[:500] if hit.text else "",
                label=config.get("label", hit.collection),
            ))

    title = request.report_title or f"Imaging Intelligence Report: {request.question[:80]}"
    generation_time_ms = (time.time() - start) * 1000

    # Handle PDF format -- return binary response
    if request.format == "pdf":
        try:
            pdf_bytes = _render_pdf_report(
                title=title,
                question=request.question,
                answer=answer,
                evidence=citations,
                search_time_ms=evidence.search_time_ms,
            )
            return Response(
                content=pdf_bytes,
                media_type="application/pdf",
                headers={
                    "Content-Disposition": (
                        f'attachment; filename="imaging_report_'
                        f'{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf"'
                    )
                },
            )
        except ImportError:
            raise HTTPException(
                status_code=501,
                detail="PDF generation requires the reportlab package",
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise HTTPException(status_code=500, detail=f"PDF generation failed: {e}")

    # Markdown or JSON format
    content = ""
    if request.format == "markdown":
        content = _render_markdown_report(
            title=title,
            question=request.question,
            answer=answer,
            evidence=citations,
            search_time_ms=evidence.search_time_ms,
        )

    return ReportResponse(
        title=title,
        generated_at=datetime.now().isoformat(),
        question=request.question,
        answer=answer,
        evidence=citations,
        evidence_count=evidence.hit_count,
        collections_searched=evidence.total_collections_searched,
        search_time_ms=evidence.search_time_ms,
        generation_time_ms=generation_time_ms,
        format=request.format,
        content=content,
    )
